{% set name = "libmediainfo" %}
{% set version = "24.03" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MediaArea/MediaInfoLib/archive/v{{ version }}.tar.gz
  sha256: 6377edff644517bb1f3683f55c150d799d82a2821b9959fca2dc6be3985f778e

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - libcurl
    - libzen >=0.4.40
    - tinyxml2
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/libmediainfo.dylib  # [osx]
    - test -f ${PREFIX}/lib/libmediainfo.so     # [linux]
    - test -f ${PREFIX}/include/MediaInfo/MediaInfo.h  # [unix]
    - IF NOT EXIST %LIBRARY_BIN%/MediaInfo.dll exit 1  # [win]
    - IF NOT EXIST %LIBRARY_INC%/MediaInfo/MediaInfo.h exit 1  # [win]

about:
  home: https://mediaarea.net
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Convenient unified display of the most relevant technical and tag data for video and audio files.
  dev_url: https://github.com/MediaArea/MediaInfoLib

extra:
  recipe-maintainers:
    - anjos
    - sodre
